name: Dockerimagecd

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on : ubuntu-latest

    steps:
        - name: Docker Login
          uses: docker/login-action@v3.2.0
          with:
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker images
          uses: docker/build-push-action@v6.2.0
          with:
            push: true
            tags: rajkumar074/zara_chatbot:latest
            
          
            
          
            

